# Generated by Django 4.2.7 on 2025-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CETExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year', models.IntegerField(unique=True)),
                ('exam_name', models.CharField(default='Karnataka Common Entrance Test', max_length=200)),
                ('application_start_date', models.DateField()),
                ('application_end_date', models.DateField()),
                ('exam_date', models.DateField()),
                ('result_date', models.DateField()),
                ('total_marks', models.IntegerField(default=540)),
                ('exam_duration_minutes', models.IntegerField(default=180)),
                ('is_active', models.BooleanField(default=True)),
                ('is_result_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_code', models.CharField(max_length=10, unique=True)),
                ('center_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
