# Generated by Django 4.2.7 on 2025-07-19 05:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('round_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('EWS', 'Economically Weaker Section')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=17)),
                ('school_name', models.CharField(max_length=200)),
                ('board', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('photo', 'Passport Size Photo'), ('10th_certificate', '10th Grade Certificate'), ('12th_certificate', '12th Grade Certificate'), ('cet_hall_ticket', 'CET Hall Ticket'), ('category_certificate', 'Category Certificate'), ('income_certificate', 'Income Certificate')], max_length=50)),
                ('document_file', models.FileField(upload_to='student_documents/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('ai_verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verification_comments', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_course', models.CharField(max_length=100)),
                ('allotment_category', models.CharField(max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allotted_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution')),
                ('counseling_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.counselinground')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CETScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket_number', models.CharField(max_length=20, unique=True)),
                ('exam_date', models.DateField()),
                ('exam_center', models.CharField(max_length=200)),
                ('physics_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('chemistry_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('mathematics_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('total_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(540)])),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('category_rank', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cet_score', to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('course_preferences', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('counseling', 'Counseling'), ('allotted', 'Seat Allotted'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='student.studentprofile')),
            ],
        ),
    ]
