# Generated by Django 4.2.7 on 2025-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentdocument_ai_verification_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatallotment',
            name='admission_order_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seatallotment',
            name='admission_order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seatallotment',
            name='choice_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatallotment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seatallotment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatallotment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seatallotment',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Payment Pending'), ('paid', 'Payment Completed'), ('failed', 'Payment Failed')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='seatallotment',
            name='student_choice',
            field=models.CharField(choices=[('choice_1', 'Choice 1: Accept Seat (Final)'), ('choice_2', 'Choice 2: Hold Seat, Try for Better'), ('choice_3', 'Choice 3: Reject Seat, Try Next Round'), ('choice_4', 'Choice 4: Exit Counselling'), ('pending', 'Pending Decision')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='seatallotment',
            name='acceptance_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
