# Generated by Django 4.2.7 on 2025-07-19 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmatrix',
            name='counseling_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.counselinground'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_matrix', to='institution.course'),
        ),
        migrations.AddField(
            model_name='institution',
            name='admin_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_institution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institution.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='seatmatrix',
            unique_together={('course', 'counseling_round')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('institution', 'course_code')},
        ),
    ]
